# Generated by Django 4.0.4 on 2022-10-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arithmeticnotesanswers',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
