# Generated by Django 4.0.5 on 2022-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_arithmeticnotesanswers_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='arithmeticUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='arithmeticnotesanswers',
            name='answer',
            field=models.FloatField(null=True),
        ),
    ]
